# Generated by Django 3.1.1 on 2020-09-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_visit_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='User_id',
            new_name='user_id',
        ),
    ]
