# Generated by Django 3.0.8 on 2020-09-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20200908_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='1', max_length=32),
            preserve_default=False,
        ),
    ]
