# Generated by Django 2.0.1 on 2020-09-06 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20200906_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='user',
            new_name='b_user',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='user',
            new_name='i_user',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='user',
            new_name='b_user',
        ),
        migrations.AddField(
            model_name='visit',
            name='i_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Individual'),
            preserve_default=False,
        ),
    ]
