# Generated by Django 2.0.1 on 2020-09-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20200906_1606'),
        ('tracking', '0003_user_password'),
    ]

    operations = [
    ]
