# Generated by Django 3.0.8 on 2020-10-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20201004_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='is_in',
        ),
        migrations.AddField(
            model_name='visit',
            name='record_type',
            field=models.CharField(choices=[('IN', 'I am sign in'), ('OUT', 'I am sign out')], default='IN', max_length=3),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
