# Generated by Django 2.0.1 on 2020-09-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20200908_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
